// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUzFQ52UV0vvxa3qQA17jZ2YKGC3rgYjg',
    appId: '1:341915135981:web:3ae2d181a037c5768a41e4',
    messagingSenderId: '341915135981',
    projectId: 'live-chat-72cb8',
    authDomain: 'live-chat-72cb8.firebaseapp.com',
    storageBucket: 'live-chat-72cb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATnkcBmIbap3YQoAHKDyjUJPh5oBNWaCE',
    appId: '1:341915135981:android:a2cf6676a61819058a41e4',
    messagingSenderId: '341915135981',
    projectId: 'live-chat-72cb8',
    storageBucket: 'live-chat-72cb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Tza27v8uM8CXruzG2fVIpy7i8_hDTm8',
    appId: '1:341915135981:ios:4ad1bc271d6dafa78a41e4',
    messagingSenderId: '341915135981',
    projectId: 'live-chat-72cb8',
    storageBucket: 'live-chat-72cb8.firebasestorage.app',
    iosBundleId: 'com.example.liveChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Tza27v8uM8CXruzG2fVIpy7i8_hDTm8',
    appId: '1:341915135981:ios:4ad1bc271d6dafa78a41e4',
    messagingSenderId: '341915135981',
    projectId: 'live-chat-72cb8',
    storageBucket: 'live-chat-72cb8.firebasestorage.app',
    iosBundleId: 'com.example.liveChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUzFQ52UV0vvxa3qQA17jZ2YKGC3rgYjg',
    appId: '1:341915135981:web:b6e14b450e34a90d8a41e4',
    messagingSenderId: '341915135981',
    projectId: 'live-chat-72cb8',
    authDomain: 'live-chat-72cb8.firebaseapp.com',
    storageBucket: 'live-chat-72cb8.firebasestorage.app',
  );
}
